# Docker compose file for running (and scaling) a set of OODT services on a single Docker host
#
# Example usage:
# docker-compose up -d
# 
# NOTE: this compose file is NOT suitable for running multiple OODT containers on a Docker swarm

version: '3.1'

services:

  oodt-filemgr:
    image: oodthub/oodt-filemgr:0.3
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./workflows/test-workflow/policy:/usr/local/oodt/workflows/policy
      # shared data volumes
      - jobs:/usr/local/oodt/jobs
      - archive:/usr/local/oodt/archive

  oodt-wmgr:
    image: oodthub/oodt-wmgr:0.3
    expose:
      - "9001"
    ports:
      - "9001:9001"
    volumes:
      - ./workflows/test-workflow/policy:/usr/local/oodt/workflows/policy
      - ./workflows/test-workflow/pge-configs:/usr/local/oodt/workflows/test-workflow/pge-configs
      - ./pges/test-workflow:/usr/local/oodt/pges/test-workflow
      # custom supervisor configuration which starts the RMQ client
      - ./conf/supervisord.conf:/etc/supervisor/supervisord.conf
      # driver program to submit workflows
      - ./rabbitmq_clients/test_workflow_driver.py:/usr/local/oodt/rabbitmq/test_workflow_driver.py
      # shared data volumes
      - jobs:/usr/local/oodt/jobs
      - archive:/usr/local/oodt/archive
    environment:
      - FILEMGR_URL=http://oodt-filemgr:9000
      - "RABBITMQ_USER_URL=amqp://oodt-user:changeit@rabbitmq/%2f"
      - "RABBITMQ_ADMIN_URL=http://oodt-admin:changeit@rabbitmq:15672"
      - "WORKFLOW_QUEUE=test-workflow"
      - "MAX_WORKFLOWS=3"
    depends_on:
      - rabbitmq

  # RabbitMQ server
  rabbitmq:
    image: oodthub/oodt-rabbitmq
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"

# shared data volumes
volumes:
  jobs:
  archive:
